version: '3.3'
services:
  mongo-database:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - '$PWD/db:/data/db'

  bitcoin-prices:
    image: bitcoin-prices:latest
    ports:
      - '8080:8080'
    environment:
      SPRING_DATA_MONGODB_HOST: "mongo-database"
      SPRING_DATA_MONGODB_PORT: "27017"
      SPRING_DATA_MONGODB_DATABASE: "db_test"
